default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: bimal
  password: bimal123

development:
  <<: *default
  database: projectInv
  username: bimal
  password: bimal123

test:
  <<: *default
  database: projectInv